git:
  quiet: true

dist: bionic
language: php
php:
    - '8.0'
os: linux
addons:
  apt:

cache:
    apt: true

before_script:

script:
    - phpize
    - ./configure --with-eio
    - make || exit 2
    - make install || exit 2
    - make test
